datasets:
  enabled: true
  logLevel: Trace
  database:
    host: mysql://ispyb-mariadb-galera-headless/ispyb
    user: ispyb_ro
    password:
      secretName: ispyb
      secretKey: password
  otelCollectorUrl: http://federation-opentelemetry-collector:4317
